In [1]:
import duckdb 
import pandas as pd

In [2]:
db = duckdb.connect('./data/duck_pond.duckdb')

In [3]:
db.execute("select * from information_schema.tables").df()

,table_catalog,table_schema,table_name,table_type,self_referencing_column_name,reference_generation,user_defined_type_catalog,user_defined_type_schema,user_defined_type_name,is_insertable_into,is_typed,commit_action,TABLE_COMMENT
0,duck_pond,source_data,pond_data,BASE TABLE,None,None,None,None,None,YES,NO,None,None
1,duck_pond,source_data,pond_data__hits,BASE TABLE,None,None,None,None,None,YES,NO,None,None
2,duck_pond,source_data,pond_data__hits__product,BASE TABLE,None,None,None,None,None,YES,NO,None,None
3,duck_pond,source_data,pond_data__hits__promotion,BASE TABLE,None,None,None,None,None,YES,NO,None,None
4,duck_pond,source_data,_dlt_loads,BASE TABLE,None,None,None,None,None,YES,NO,None,None
5,duck_pond,source_data,_dlt_pipeline_state,BASE TABLE,None,None,None,None,None,YES,NO,None,None
6,duck_pond,source_data,_dlt_version,BASE TABLE,None,None,None,None,None,YES,NO,None,None